### ISSUE TITLE
Build / Install fails

### ISSUE THREAD

**Issue by rabble** [quentintaranpino/nostrcheck-api-ts#8]
**Describe the bug**
When installing app from install scripts the build fails a few places. First there's no instructions to run the initialize.sh script. But a bigger issue is npm run install fails. 

**To Reproduce**
1. Start with fresh debian install
2. Run install.sh
3. Run initalize.sh 
4. Run npm run start
5. See error

**Expected behavior**
It should be able to find canvas.node but it can't... This prevents the app from running.

**Additional context**

npm run start

> nostrcheck-api-ts@0.4.2 start
> node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm ./dist/server.js

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /root/nostrcheck-api-ts/node_modules/canvas/lib/bindings.js
- /root/nostrcheck-api-ts/node_modules/canvas/lib/canvas.js
- /root/nostrcheck-api-ts/node_modules/canvas/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/root/nostrcheck-api-ts/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/root/nostrcheck-api-ts/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (/root/nostrcheck-api-ts/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/nostrcheck-api-ts/node_modules/canvas/lib/bindings.js',
    '/root/nostrcheck-api-ts/node_modules/canvas/lib/canvas.js',
    '/root/nostrcheck-api-ts/node_modules/canvas/index.js'
  ]
}

**Comment by quentintaranpino** [comment]
Hello, 

I just did a quick test on a clean debian and I am unable to reproduce it, anyway a small clarification, intialize.sh must be run after running the server at least once. However that does not cause the error you describe. 

Canvas should be installed on the first npm install running install.sh

Please, could you try to manually run npm install?

**Comment by quentintaranpino** [comment]
Solved here: https://github.com/quentintaranpino/nostrcheck-api-ts/commit/092d2faae43104c5258e32f7139cd7f6ba24f642  It was a problem with updates of other packages that generated inconsistencies and incompatibilities. 

Thank you very much for opening the issue
